# This is a basic workflow to help you get started with Actions

name: Win1

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tun:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        # secret needs to be like: T xxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxx eu.relay.tunshell.com
        run:  | 
          Invoke-WebRequest -Uri 'https://lets.tunshell.com/init.ps1' -OutFile init.ps1
          cmd.exe /c start powershell -ExecutionPolicy bypass -c ".\init.ps1 ${{ secrets.WIN1 }}"
